version: '3'
services:
  app:
    build: .
    # volumes:
    #   - ./jobs:/jobs
    #   - ./config:/config
    command: tail -F anything
    environment:
    - ENV=Development

volumes:
  my_volume:
    external: true
